apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nodejs-bxsuuqzv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-bxsuuqzv 
  name: nodejs-bxsuuqzv
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-bxsuuqzv
    weight: 100 
